---
title: "Olympics"
author: "Madrine"
format: 
  dashboard: 
    orientation: columns

editor: visual
---



```{r}
#| label: load-packages
library(tidyverse)
library(gt)
```

```{r}
#| label: load-data
#| message: false
olympics_full <- read_csv("data/olympics.csv")
```

```{r}
#| label: prep-data
olympics <- olympics_full |>
  filter(!is.na(medal)) |>
  separate_wider_delim(
    cols = team, 
    names = c("team", "suffix"),
    delim = "-", 
    too_many = "merge", 
    too_few = "align_start") |>
  select(-suffix) |>
  mutate(medal = fct_relevel(medal, "Bronze", "Silver", "Gold"))

```

```{r}
#| label: medals-by-sport
#| title: Medals by sport
#| fig-width: 10
#| fig-asp: 0.618
olympics |>
  mutate(
    sport = fct_lump_n(sport, n = 15),
    sport = fct_infreq(sport),
    sport = fct_rev(sport),
    sport = fct_relevel(sport, "Other", after = 0)
  ) |>
  ggplot(aes(y = sport, fill = medal)) +
  geom_bar() +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(
    x = NULL,
    y = NULL,
    fill = "Medal"
  ) +
  theme_minimal() +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.9, 0.2),
    legend.direction = "horizontal",
    legend.background = element_rect(fill = "white", color = "gray")
  )
```

```{r}
#| label: medals-by-year
#| title: Medals by year
#| fig-asp: 0.3
#| fig-width: 10
olympics |>
  count(year, medal) |>
  ggplot(aes(x = year, y = n, color = medal)) +
  geom_point(size = 0.5) +
  geom_line() +
  guides(color = guide_legend(reverse = TRUE)) +
  scale_x_continuous(breaks = seq(1896, 2020, 8)) +
  labs(
    x = "Year",
    y = NULL,
    color = "Medal"
  ) +
  theme_minimal() +
  theme(
    legend.position = "inside",
    legend.position.inside = c(0.9, 0.2),
    legend.direction = "horizontal",
    legend.background = element_rect(fill = "white", color = "gray")
  )
```

```{r}
#| label: summer-calculate-most-medals
summer_most_golds <- olympics |>
  filter(medal == "Gold") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)

summer_most_silvers <- olympics |>
  filter(medal == "Silver") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)

summer_most_bronzes <- olympics |>
  filter(medal == "Bronze") |>
  count(team, sort = TRUE) |>
  slice_head(n = 1)
```


::: {.valuebox icon="award-fill" color="#d4af37"}
Most golds:

`{r} summer_most_golds$n`

`{r} as.character(summer_most_golds$team)`
:::

::: {.valuebox icon="award-fill" color="#c0c0c0"}
Most silvers:

`{r} summer_most_silvers$n`

`{r} as.character(summer_most_silvers$team)`
:::

::: {.valuebox icon="award-fill" color="#cd7f32"}
Most bronzes:

`{r} summer_most_bronzes$n`

`{r} as.character(summer_most_bronzes$team)`
:::

::: {.valuebox icon="award-fill" color="#d4af37"}
Most golds:

`{r} summer_most_golds$n`

`{r} as.character(summer_most_golds$team)`
:::

::: {.valuebox icon= "award-fill" colour = "skyblue"}
most golds:
`{r} summer_most_golds$n`
`{r} as.character(summer_most_golds$team)`
:::


